[project]
name = "powercenter-to-databricks-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chromadb>=1.5.9",
    "faiss-cpu>=1.15.0",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-groq>=1.1.3",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.0",
    "langchain-text-splitters>=1.1.2",
    "langchain-unstructured>=1.0.1",
    "pypdf>=6.17.0",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "unstructured-inference>=1.6.13",
    "unstructured[pdf]>=0.27.5",
]

[project.scripts]
powercenter-to-databricks-agent = "powercenter_to_databricks_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
